<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Quote\Module'                        => __DIR__ . '/Module.php',
    'Quote\Controller\SearchController' => __DIR__ . '/src/Quote/Controller/SearchController.php',
    'QuoteTest\Framework\TestCase'        => __DIR__ . '/tests/Quote/Framework/TestCase.php',
    'QuoteTest\SampleTest'                => __DIR__ . '/tests/Quote/SampleTest.php',
);
