<?php

$this->headLink()->appendStylesheet('/css/delete.css');
$title = 'Delete Customer';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete Customer: <?php echo $this->escapeHtml($customer->customer_name); ?>?
</p>
<?php
$url = $this->url('customer/default', array('controller'=>'update',
    'action' => 'delete',
    
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $customer->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
