<?php


$title = 'Delete Invoice';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete invoice
    <?php echo $this->escapeHtml($row->id); ?> invoice number: <?php echo $this->escapeHtml($row->invoice_number); ?>?
</p>
<?php
$url = $this->url('invoice/default', array('controller'=>'create',
    'action' => 'delete',
    
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $row->id; ?>" />
   
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
