<?php


$title = 'Delete album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete item
    '<?php echo $this->escapeHtml($this->catalogNo); ?>'?
</p>
<?php
$url = $this->url('catalog/default', array('controller'=>'update',
    'action' => 'delete',
    
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="catalogNo" value="<?php echo $this->catalogNo; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
