<?php


$title = 'Delete Cost Item';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete cost item
    <?php echo $this->escapeHtml($row->cost_name); ?> : <?php echo $this->escapeHtml($row->cost_description); ?>?
</p>
<?php
$url = $this->url('order/default', array('controller'=>'cost',
    'action' => 'delete',
    
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $row->id; ?>" />
  
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
