<?php


$title = 'Delete Order';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete order
    <?php echo $this->escapeHtml($row->id); ?> PO_Number: <?php echo $this->escapeHtml($row->PO_Number); ?>?
</p>
<?php
$url = $this->url('order/default', array('controller'=>'update',
    'action' => 'delete',
    
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo $row->id; ?>" />
   
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
