<?php
$this->headLink()->appendStylesheet('/css/showitems.css');
if ($this->form)
{
    $form=$this->form;
    $form->setAttribute('action', $this->url('catalog/default', array('controller'=>'search','action'=>'search')));
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formCollection($form);
    echo $this->form()->closeTag();
}else 
if ($this->rowset)

{
    $url=$this->url('catalog/default', array('controller'=>'search', 'action'=>'show'));
    $output='';
    $output.=
    		'<table cellpadding="5" cellspacing="5"  >'.
    		
    		' <tr >'.
    		'<th align="center">Description</th>'.
    		'<th align="center">Structure</th>'.
    		'<th align="center">Catalog Number</th>'.
    		'</tr>';
    foreach ($this->rowset as $item)
    {
    	$output.= '<tr >'
    			.'<td align="center"><a href="'.$url.'?catalogNo='.$item->catalogNo.'">'.$item->name
    			.'</a><br/>CAS No.:&nbsp; <a href="'.$url.'?catalogNo='.$item->catalogNo.'">'.$item->cas.'</a></td>'
    					.'<td align="center"><a href="'.$url.'?catalogNo='.$item->catalogNo.'">'
    							.'<IMG src="/img/mol/'.$item->catalogNo.'.png" width="100px" height="100px"  style="padding:10px;"/></a></td>'
    									.'<td align="center"><a href="'.$url.'?catalogNo='.$item->catalogNo.'">'.$item->catalogNo.'</a></td>'
    											.'</tr>';
    }
    $output.= '</tr>'
    		
    		.'</table>';
    echo $output;
    			
}


    