<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Invoice\Module'                        => __DIR__ . '/Module.php',
    'Invoice\Controller\CreateController' => __DIR__ . '/src/Invoice/Controller/CreateController.php',
    'InvoiceTest\Framework\TestCase'        => __DIR__ . '/tests/Invoice/Framework/TestCase.php',
    'InvoiceTest\SampleTest'                => __DIR__ . '/tests/Invoice/SampleTest.php',
);
